// Test-Mails (erfunden).

export const sampleReply = [
  "From: Petra Schulz <p.schulz@moebelhaus.example>",
  "To: Anna Beispiel <anna@example.test>",
  "Subject: =?UTF-8?Q?Gr=C3=BC=C3=9Fe_aus_M=C3=BCnchen?=",
  "Date: Tue, 29 Sep 2026 10:00:00 +0200",
  "Message-ID: <m1@moebelhaus.example>",
  "In-Reply-To: <m0@example.test>",
  "References: <m0@example.test>",
  "MIME-Version: 1.0",
  'Content-Type: multipart/mixed; boundary="XYZ"',
  "",
  "--XYZ",
  'Content-Type: multipart/alternative; boundary="ALT"',
  "",
  "--ALT",
  "Content-Type: text/plain; charset=utf-8",
  "Content-Transfer-Encoding: 8bit",
  "",
  "Hallo Anna,",
  "",
  "anbei das Angebot.",
  "",
  "Am 28.09.2026 schrieb Anna:",
  "> Kannst du mir das Angebot schicken?",
  "--ALT",
  "Content-Type: text/html; charset=utf-8",
  "",
  "<p>Hallo Anna,</p><p>anbei das <b>Angebot</b>.</p><img src=\"https://tracker.example/pixel.gif\">",
  "--ALT--",
  "--XYZ",
  'Content-Type: application/pdf; name="Angebot.pdf"',
  'Content-Disposition: attachment; filename="Angebot.pdf"',
  "Content-Transfer-Encoding: base64",
  "",
  Buffer.from("%PDF-1.4 test").toString("base64"),
  "--XYZ--",
  "",
].join("\r\n");
